/* The trained model, in the browser.
 *
 * The book answers the opening — positions he actually reached, twice or more.
 * This answers everything after it, which used to be raw Stockfish and had
 * nothing to do with him.
 *
 * THE ENCODING HERE MUST MATCH `train/encoding.py` SQUARE FOR SQUARE. Two
 * implementations of one contract is the standing risk: a mismatch throws no
 * error, the network simply receives a board it was never trained on and plays
 * nonsense. Two things hold it together — the move vocabulary is FETCHED from
 * the file the labels were built from rather than re-derived, and
 * `personality.test.js` checks this encoder against planes generated by the
 * Python one (`src/play/__fixtures__/encoding.json`).
 */

import { Chess } from '../lib/rules.js'

/* `import.meta.env` is Vite's and does not exist under node, where the encoder
   is unit-tested against the Python fixture. Guarded so importing this module
   outside a bundle does not throw before a single test runs. */
const BASE = import.meta.env?.BASE_URL ?? '/'
const MODEL_URL = `${BASE}models/personality.onnx`
const MOVES_URL = `${BASE}models/moves.json`
const META_URL = `${BASE}models/personality.json`

export const N_PLANES = 18

/* Plane order, from train/encoding.py:
 *   0-5   our pawn knight bishop rook queen king
 *   6-11  theirs, same order
 *   12    side to move (all ones when white)
 *   13-16 castling: our king, our queen, their king, their queen
 *   17    en-passant target
 * Planes 0-11 are written from the SIDE TO MOVE's perspective, with the board
 * mirrored when black moves — so the net only ever learns one point of view. */
const ROLE_PLANE = { p: 0, n: 1, b: 2, r: 3, q: 4, k: 5 }

const mirror = (sq) => sq ^ 56 // rank flip, file kept — chess.square_mirror

/* 'e4' -> 28, matching python-chess's square numbering (a1 = 0). */
const squareIndex = (name) => (name.charCodeAt(1) - 49) * 8 + (name.charCodeAt(0) - 97)

export const encodeBoard = (chess) => {
  const planes = new Float32Array(N_PLANES * 64)
  const white = chess.turn() === 'w'
  const flip = !white

  for (const row of chess.board()) {
    for (const piece of row) {
      if (!piece) continue
      const sq = flip ? mirror(squareIndex(piece.square)) : squareIndex(piece.square)
      const ours = (piece.color === 'w') === white
      planes[(ROLE_PLANE[piece.type] + (ours ? 0 : 6)) * 64 + sq] = 1
    }
  }

  if (white) planes.fill(1, 12 * 64, 13 * 64)

  /* Castling rights come off the FEN field — `KQkq` — and are ordered ours
     first, which is the side to move, not white. */
  const rights = chess.fen().split(' ')[2]
  const has = (c) => (rights.includes(c) ? 1 : 0)
  const ourK = white ? 'K' : 'k'
  const ourQ = white ? 'Q' : 'q'
  const theirK = white ? 'k' : 'K'
  const theirQ = white ? 'q' : 'Q'
  if (has(ourK)) planes.fill(1, 13 * 64, 14 * 64)
  if (has(ourQ)) planes.fill(1, 14 * 64, 15 * 64)
  if (has(theirK)) planes.fill(1, 15 * 64, 16 * 64)
  if (has(theirQ)) planes.fill(1, 16 * 64, 17 * 64)

  const ep = chess.fen().split(' ')[3]
  if (ep && ep !== '-') {
    const sq = flip ? mirror(squareIndex(ep)) : squareIndex(ep)
    planes[17 * 64 + sq] = 1
  }

  return planes
}

/* A move's index in the exported vocabulary. Queen promotion is the BARE move
 * — the vocabulary holds `e7e8` plus the three underpromotions, never `e7e8q`
 * — which is the same rule train/encoding.py applies when writing a label. */
export const moveKey = (move, flip) => {
  let from = squareIndex(move.from)
  let to = squareIndex(move.to)
  if (flip) {
    from = mirror(from)
    to = mirror(to)
  }
  const name = (i) => String.fromCharCode(97 + (i % 8)) + String.fromCharCode(49 + Math.floor(i / 8))
  const promo = move.promotion && move.promotion !== 'q' ? move.promotion : ''
  return name(from) + name(to) + promo
}

export const normaliseRating = (elo, lo = 1100, hi = 1900) =>
  Math.min(Math.max((elo - lo) / (hi - lo), 0), 1)

/* ── the session ─────────────────────────────────────────────────────────── */

let sessionPromise = null
/* ONE FAILURE IS FINAL, not one per move. `sessionPromise` used to be cleared
   on error so the next move retried — which, with no model shipped, meant a
   404 and a wasm boot attempt on every single reply for the whole game. If the
   model is not there, it is not going to appear mid-game. */
let unavailable = false

/* onnxruntime-web is ~14 MB of wasm plus a 9 MB model, so nothing loads until
   a game actually needs a move out of book. Same rule as the books. */
export const loadModel = () => {
  if (unavailable) return Promise.reject(new Error('model unavailable'))
  if (sessionPromise) return sessionPromise
  sessionPromise = (async () => {
    const ort = await import('onnxruntime-web')
    /* NO `wasmPaths` OVERRIDE. Pointing it at a copy in `public/` looks tidy and
       does not work: the runtime reaches its wasm through a dynamic import, Vite
       marks that request `?import`, and a file served raw out of `public/` cannot
       answer a module request — it 500s and the model silently never loads.
       Left alone, the assets resolve through the module graph, which Vite serves
       in dev and Rollup emits at build. */
    ort.env.wasm.numThreads = 1
    const [session, moves, meta] = await Promise.all([
      ort.InferenceSession.create(MODEL_URL, { executionProviders: ['wasm'] }),
      fetch(MOVES_URL).then((r) => r.json()),
      fetch(META_URL).then((r) => (r.ok ? r.json() : null)).catch(() => null)
    ])
    const index = new Map(moves.map((uci, i) => [uci, i]))
    return { ort, session, index, meta }
  })().catch((err) => {
    unavailable = true
    sessionPromise = null
    throw err
  })
  return sessionPromise
}

/**
 * Ask the model for a move.
 *
 * `elo` is the strength dial: the SAME network answers differently at 1200 and
 * 1900 because the rating rides in as an input plane. `temperature` decides how
 * closely it sticks to its favourite — 0 is always the top move, higher lets
 * the less likely ones through, which is what stops every game being identical.
 */
export const modelMove = async (fen, { elo = 1600, temperature = 0.9 } = {}) => {
  const { ort, session, index } = await loadModel()
  const chess = new Chess(fen)
  const legal = chess.moves({ verbose: true })
  if (!legal.length) return null

  const flip = chess.turn() === 'b'
  const board = encodeBoard(chess)
  const rating = Float32Array.from([normaliseRating(elo)])

  const out = await session.run({
    board: new ort.Tensor('float32', board, [1, N_PLANES, 8, 8]),
    rating: new ort.Tensor('float32', rating, [1, 1])
  })
  const logits = out.policy.data

  /* MASK TO LEGAL MOVES. The head scores all 1858 entries and has no idea
     which are playable here; taking its argmax outright plays illegal moves. */
  const scored = []
  let max = -Infinity
  for (const m of legal) {
    const i = index.get(moveKey(m, flip))
    if (i === undefined) continue
    const v = logits[i]
    scored.push({ move: m, logit: v })
    if (v > max) max = v
  }
  if (!scored.length) return null

  if (temperature <= 0) {
    const best = scored.reduce((a, b) => (b.logit > a.logit ? b : a))
    return { san: best.move.san, from: best.move.from, to: best.move.to, promotion: best.move.promotion }
  }

  let total = 0
  for (const s of scored) {
    s.p = Math.exp((s.logit - max) / temperature)
    total += s.p
  }
  let r = Math.random() * total
  for (const s of scored) {
    r -= s.p
    if (r <= 0) {
      return {
        san: s.move.san,
        from: s.move.from,
        to: s.move.to,
        promotion: s.move.promotion,
        share: s.p / total
      }
    }
  }
  const last = scored[scored.length - 1]
  return { san: last.move.san, from: last.move.from, to: last.move.to, promotion: last.move.promotion }
}
